package com.cogninus.bootmvc.models;

// Generated Apr 1, 2017 1:20:47 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OmsIdAttributesId generated by hbm2java
 */
@Embeddable
public class OmsIdAttributesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6619697906478099758L;
	private String code;
	private String category;

	public OmsIdAttributesId() {
	}

	public OmsIdAttributesId(String code, String category) {
		this.code = code;
		this.category = category;
	}

	@Column(name = "CODE", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CATEGORY", nullable = false, length = 20)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OmsIdAttributesId))
			return false;
		OmsIdAttributesId castOther = (OmsIdAttributesId) other;

		return ((this.getCode() == castOther.getCode()) || (this.getCode() != null
				&& castOther.getCode() != null && this.getCode().equals(
				castOther.getCode())))
				&& ((this.getCategory() == castOther.getCategory()) || (this
						.getCategory() != null
						&& castOther.getCategory() != null && this
						.getCategory().equals(castOther.getCategory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getCategory() == null ? 0 : this.getCategory().hashCode());
		return result;
	}

}
