package com.cogninus.bootmvc.models;

// Generated Apr 1, 2017 1:20:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OmsIdsDelete generated by hbm2java
 */
@Entity
@Table(name = "OMS_IDS_DELETE")
public class OmsIdsDelete implements java.io.Serializable {

	
	private static final long serialVersionUID = -5962551055145575229L;
	private String id;
	private String idType;
	private String channeltype;
	private String architecture;
	private String asset;
	private String isactive;
	private String description;
	private String createUser;
	private Date createDate;
	private String updateUser;
	private Date updateDate;
	private String offername;
	private String offerLanguage;
	private String channelname;
	private String socialchannel;
	private String audience;
	private Date livedate;
	private Date expirydate;
	private String url;
	private String assetid;
	private String country;
	private String vertical;
	private String offerstage;
	private String deleteUser;
	private String deleteDate;
	private String marketprogram;
	private String campaignstrategy;

	public OmsIdsDelete() {
	}

	public OmsIdsDelete(String id, String idType, String isactive) {
		this.id = id;
		this.idType = idType;
		this.isactive = isactive;
	}

	public OmsIdsDelete(String id, String idType, String channeltype,
			String architecture, String asset, String isactive,
			String description, String createUser, Date createDate,
			String updateUser, Date updateDate, String offername,
			String offerLanguage, String channelname, String socialchannel,
			String audience, Date livedate, Date expirydate, String url,
			String assetid, String country, String vertical, String offerstage,
			String deleteUser, String deleteDate, String marketprogram,
			String campaignstrategy) {
		this.id = id;
		this.idType = idType;
		this.channeltype = channeltype;
		this.architecture = architecture;
		this.asset = asset;
		this.isactive = isactive;
		this.description = description;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
		this.offername = offername;
		this.offerLanguage = offerLanguage;
		this.channelname = channelname;
		this.socialchannel = socialchannel;
		this.audience = audience;
		this.livedate = livedate;
		this.expirydate = expirydate;
		this.url = url;
		this.assetid = assetid;
		this.country = country;
		this.vertical = vertical;
		this.offerstage = offerstage;
		this.deleteUser = deleteUser;
		this.deleteDate = deleteDate;
		this.marketprogram = marketprogram;
		this.campaignstrategy = campaignstrategy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ID_TYPE", nullable = false, length = 20)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "CHANNELTYPE", length = 4)
	public String getChanneltype() {
		return this.channeltype;
	}

	public void setChanneltype(String channeltype) {
		this.channeltype = channeltype;
	}

	@Column(name = "ARCHITECTURE", length = 4)
	public String getArchitecture() {
		return this.architecture;
	}

	public void setArchitecture(String architecture) {
		this.architecture = architecture;
	}

	@Column(name = "ASSET", length = 3)
	public String getAsset() {
		return this.asset;
	}

	public void setAsset(String asset) {
		this.asset = asset;
	}

	@Column(name = "ISACTIVE", nullable = false, length = 1)
	public String getIsactive() {
		return this.isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Column(name = "DESCRIPTION", length = 2700)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATE_USER", length = 20)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_USER", length = 20)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "OFFERNAME", length = 170)
	public String getOffername() {
		return this.offername;
	}

	public void setOffername(String offername) {
		this.offername = offername;
	}

	@Column(name = "OFFER_LANGUAGE", length = 20)
	public String getOfferLanguage() {
		return this.offerLanguage;
	}

	public void setOfferLanguage(String offerLanguage) {
		this.offerLanguage = offerLanguage;
	}

	@Column(name = "CHANNELNAME", length = 4)
	public String getChannelname() {
		return this.channelname;
	}

	public void setChannelname(String channelname) {
		this.channelname = channelname;
	}

	@Column(name = "SOCIALCHANNEL", length = 4)
	public String getSocialchannel() {
		return this.socialchannel;
	}

	public void setSocialchannel(String socialchannel) {
		this.socialchannel = socialchannel;
	}

	@Column(name = "AUDIENCE", length = 4)
	public String getAudience() {
		return this.audience;
	}

	public void setAudience(String audience) {
		this.audience = audience;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LIVEDATE", length = 7)
	public Date getLivedate() {
		return this.livedate;
	}

	public void setLivedate(Date livedate) {
		this.livedate = livedate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRYDATE", length = 7)
	public Date getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(Date expirydate) {
		this.expirydate = expirydate;
	}

	@Column(name = "URL", length = 1200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ASSETID", length = 170)
	public String getAssetid() {
		return this.assetid;
	}

	public void setAssetid(String assetid) {
		this.assetid = assetid;
	}

	@Column(name = "COUNTRY", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "VERTICAL", length = 20)
	public String getVertical() {
		return this.vertical;
	}

	public void setVertical(String vertical) {
		this.vertical = vertical;
	}

	@Column(name = "OFFERSTAGE", length = 4)
	public String getOfferstage() {
		return this.offerstage;
	}

	public void setOfferstage(String offerstage) {
		this.offerstage = offerstage;
	}

	@Column(name = "DELETE_USER", length = 20)
	public String getDeleteUser() {
		return this.deleteUser;
	}

	public void setDeleteUser(String deleteUser) {
		this.deleteUser = deleteUser;
	}

	@Column(name = "DELETE_DATE", length = 20)
	public String getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(String deleteDate) {
		this.deleteDate = deleteDate;
	}

	@Column(name = "MARKETPROGRAM", length = 20)
	public String getMarketprogram() {
		return this.marketprogram;
	}

	public void setMarketprogram(String marketprogram) {
		this.marketprogram = marketprogram;
	}

	@Column(name = "CAMPAIGNSTRATEGY", length = 4)
	public String getCampaignstrategy() {
		return this.campaignstrategy;
	}

	public void setCampaignstrategy(String campaignstrategy) {
		this.campaignstrategy = campaignstrategy;
	}

}
