package com.cogninus.bootmvc.models;

// Generated Apr 1, 2017 1:20:47 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OmsUsers generated by hbm2java
 */
@Entity
@Table(name = "OMS_USERS")
public class OmsUsers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7823604524013717180L;
	private String userId;
	private BigDecimal userGrpId;
	private String firstName;
	private String lastName;
	private String middleName;
	private String ciscoUserId;
	private String ciscoEmailId;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date modifiedDate;
	private String adminFlag;
	private String ccidFlag;

	public OmsUsers() {
	}

	public OmsUsers(String userId, BigDecimal userGrpId) {
		this.userId = userId;
		this.userGrpId = userGrpId;
	}

	public OmsUsers(String userId, BigDecimal userGrpId, String firstName,
			String lastName, String middleName, String ciscoUserId,
			String ciscoEmailId, String createdBy, Date createdDate,
			String modifiedBy, Date modifiedDate, String adminFlag,
			String ccidFlag) {
		this.userId = userId;
		this.userGrpId = userGrpId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.ciscoUserId = ciscoUserId;
		this.ciscoEmailId = ciscoEmailId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.adminFlag = adminFlag;
		this.ccidFlag = ccidFlag;
	}

	@Id
	@Column(name = "USER_ID", unique = true, nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_GRP_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUserGrpId() {
		return this.userGrpId;
	}

	public void setUserGrpId(BigDecimal userGrpId) {
		this.userGrpId = userGrpId;
	}

	@Column(name = "FIRST_NAME", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MIDDLE_NAME", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "CISCO_USER_ID", length = 20)
	public String getCiscoUserId() {
		return this.ciscoUserId;
	}

	public void setCiscoUserId(String ciscoUserId) {
		this.ciscoUserId = ciscoUserId;
	}

	@Column(name = "CISCO_EMAIL_ID", length = 100)
	public String getCiscoEmailId() {
		return this.ciscoEmailId;
	}

	public void setCiscoEmailId(String ciscoEmailId) {
		this.ciscoEmailId = ciscoEmailId;
	}

	@Column(name = "CREATED_BY", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "ADMIN_FLAG", length = 20)
	public String getAdminFlag() {
		return this.adminFlag;
	}

	public void setAdminFlag(String adminFlag) {
		this.adminFlag = adminFlag;
	}

	@Column(name = "CCID_FLAG", length = 20)
	public String getCcidFlag() {
		return this.ccidFlag;
	}

	public void setCcidFlag(String ccidFlag) {
		this.ccidFlag = ccidFlag;
	}

}
